name: AnneServer Update Achieve Release

on:
  push:
    branches:
      - 'main'

jobs:

  release:
    if: github.repository == 'Caibiii/AnneServer'
    name: Upload  AnneServer Achieve if a new commit was been push.
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/Caibiii/AnneServer.git
      
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Gzip
        run: |
          mkdir AnneServer-stable-$NOW
          cp -R AnneServer AnneServer-stable-$NOW
          tar -czvf  AnneServer-stable-$NOW.tar.gz  AnneServer-stable-$NOW

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args:  AnneServer-stable-NOW.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
