name: AnneServer Update Achieve Release

on:
  push:
    branches:
      - 'main'

jobs:

  release:
    if: github.repository == 'Caibiii/AnneServer'
    name: Upload  AnneServer Achieve if a new commit was been push.
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/Caibiii/AnneServer.git

      - name: Gzip
        run: |
          mkdir AnneServer-stable-${date}
          cp -R AnneServer AnneServer-stable-${date}
          tar -czvf  AnneServer-stable-${date}.tar.gz  AnneServer-stable-${date}

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args:  AnneServer-stable-${date}.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
